### ISSUE TITLE
{errorMessage: Network(s) failed to load ad, errorCode: 130}

### ISSUE THREAD

**Issue by chounry** [nathanael540/tapdaq_flutter#2]
I try to display a banner and that error happen. 

What I have setup :
- Create an app on Google AdMob.
- Setup Ad Unit for banner and copy the Unit Id to the Tapdaq -> Demand Sources.
- Done adding `implementation 'com.tapdaq.sdk:TapdaqAdMobAdapter:7.7.0'` to android gradle.
- I have run this in the init state 

```
Tapdaq tapdaq = Tapdaq(
      appId: 'my-app-id',
      clientKey: 'my-client-key',
    );

tapdaq.initialize();
```
- put this in the widget(adTag, I get it from the Tapdaq dashbaord)
```
TapdaqBanner(
          adTag: "test",
          adSize: TapdaqBannerSize.LARGE,
          listener: (event, what) {
            print("BANNER EVENT $event");
            print("BANNER MSG $what");
          },
          onBannerCreated: (controller) {
            print("Controller $controller");
          },
        )
```
How can i fix this?

**Comment by willmeet** [comment]
issue clearly described here http://www.technologymanias.com/2020/10/admob-ads-failed-to-load-ads-solve-this.html

**Comment by chounry** [comment]
I have figure it out. It's because of the size of banner get from the ads provider and the banner size that we choose for displaying is not the same.
