### ISSUE TITLE
Tapdaq not initialised

### ISSUE THREAD

**Issue by ahammamlho** [nathanael540/tapdaq_flutter#3]
I'm using tapdaq (tapdaq_flutter) to monetize my android - flutter app  it faild to   initialised  Tapdaq   What am I doing wrong??

Tapdaq tapdaq = Tapdaq(
      appId: 'my-app-id',
      clientKey: 'my-client-key',
     @);
tapdaq.initialize();

help me please :'(

**Comment by nathanael540** [comment]
Hi, this package has not been updated for over 16 months.

I believe there must be a lot of bugs because the libraries are out of date, and I don't do maintenance anymore.

Feel free to debug the cause, fix it and add a pull with the fix for other people who still insist on using it.
